"""11.01.2024-15:06:29

Revision ID: 91b600bdd5cd
Revises: c5331cc8b103
Create Date: 2024-01-11 15:06:41.833579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b600bdd5cd'
down_revision: Union[str, None] = 'c5331cc8b103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('link_tg', sa.String(length=128), nullable=False))
    op.add_column('links', sa.Column('pdf_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'pdf_id')
    op.drop_column('links', 'link_tg')
    # ### end Alembic commands ###
