"""07.01.2024-14:51:02

Revision ID: e393aa971f62
Revises: 43d7289cdf26
Create Date: 2024-01-07 14:51:05.512006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e393aa971f62'
down_revision: Union[str, None] = '43d7289cdf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
